"""Added Onestop description field to Class Distribution

Revision ID: 6a072b3ea585
Revises: 277a6d58ebd5
Create Date: 2023-06-10 15:15:38.710150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a072b3ea585'
down_revision = '277a6d58ebd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classdistribution', sa.Column('onestop_desc', sa.VARCHAR(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classdistribution', 'onestop_desc')
    # ### end Alembic commands ###
