"""Added columns to be filled by SQLAlchemy Parsing

Revision ID: b1c8ca7029a6
Revises: 6a072b3ea585
Create Date: 2024-04-26 16:28:02.404470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c8ca7029a6'
down_revision = '6a072b3ea585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classdistribution', sa.Column('campus', sa.VARCHAR(length=8), nullable=True))
    op.add_column('classdistribution', sa.Column('dept_abbr', sa.VARCHAR(length=4), nullable=True))
    op.add_column('classdistribution', sa.Column('course_num', sa.VARCHAR(length=4), nullable=True))
    op.add_column('departmentdistribution', sa.Column('campus', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departmentdistribution', 'campus')
    op.drop_column('classdistribution', 'course_num')
    op.drop_column('classdistribution', 'dept_abbr')
    op.drop_column('classdistribution', 'campus')
    # ### end Alembic commands ###
