"""Added x500 Column for Professor

Revision ID: bde13d04cf22
Revises: 21b224ea9306
Create Date: 2023-06-10 15:02:00.503542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde13d04cf22'
down_revision = '21b224ea9306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('x500', sa.VARCHAR(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professor', 'x500')
    # ### end Alembic commands ###
