"""
This file has constant definitions for mappings from deptartment abbreviations to their actual name,
libed mapping from their abbreviations to actual name, and grade mapping from letters to GPA.
These may need to be edited manually on the creation of new departments, or changes to libed names but
these are infrequent and can be done by hand.
"""
dept_mapping = {
    'AAS': 'Asian American Studies',
    'ABUS': 'Applied Business',
    'ACCT': 'Accounting',
    'ACL': 'Arts and Cultural Leadership',
    'ADDS': 'Addiction Studies',
    'ADES': 'Apparel Design',
    'ADPY': 'Adult Psychiatry',
    'AECM': 'Ag Educ, Comm & Mktg',
    'AEM': 'Aerospace Engineering and Mech',
    'AFEE': 'Agriculture, Food, and Environment Education',
    'AFRO': 'African Amer & African Studies',
    'AGRO': 'Agronomy and Plant Genetics',
    'AHS': 'Academic Health Center Shared',
    'AIM': 'Agricultural Industries and Marketing',
    'AIR': 'Aerospace Studies',
    "ALL": 'Asian Languages and Literature',
    'AMES': 'Asian & Middle Eastern Studies',
    'AMIN': 'American Indian Studies',
    'AMST': 'American Studies',
    'ANAT': 'Anatomy',
    'ANES': 'Anesthesiology',
    'ANSC': 'Animal Science',
    'ANTH': 'Anthropology',
    'APEC': 'Applied Economics',
    'APS': 'Applied Professional Studies',
    'APSC': 'Applied Plant Sciences',
    'APST': 'Apparel Studies',
    'ARAB': 'Arabic',
    'ARCH': 'Architecture',
    'ARGN': 'Study Abroad in Argentina',
    'ARTH': 'Art History',
    'ARTS': 'Art',
    'ASCL': 'Applied Sciences Leadership',
    'ASL': 'American Sign Language',
    'AST': 'Astronomy',
    'BA': 'Business Administration',
    'BBE': 'Bioproducts and Biosystems Eng',
    'BCLA': 'CAPA Barcelona Study Abr Prgm',
    'BIOC': 'Biochemistry',
    'BIOL': 'Biology',
    'BLAW': 'Business Law',
    'BMEN': 'Biomedical Engineering',
    'BSE': 'Biology, Society, and Environ',
    'BTHX': 'Bioethics, Center for',
    'CAPY': 'Child & Adolescent Psychiatry',
    'CDED': 'Continuing Dental Education',
    'CEGE': 'Civil, Environ, and Geo-Engin',
    'CESP': 'Commun Engage Scholars Program',
    'CFAN': 'Col of Food, Agr & Nat Res Sci',
    'CGSC': 'Cognitive Science',
    'CHEM': 'Chemistry',
    'CHEN': 'Chemical Engineering',
    'CHIC': 'Chicano Studies',
    'CHMB': 'China Executive MBA',
    'CHN': 'Chinese',
    'CHPH': 'Chemical Physics',
    'CI': 'Curriculum and Instruction',
    'CIVE': 'Civic Engagement',
    'CL': 'Comparative Literature',
    'CLA': 'College of Liberal Arts',
    'CMB': 'Comparative & Molecular Biosci',
    'CMBA': 'Carlson Executive MBA',
    'CMGT': 'Construction Management',
    'CNES': 'Classical and Near Eastern Religions and Cultures',
    'CNRC': 'Classical/Near Eastern Rel/Cul',
    'COMM': 'Communication Studies',
    'CONS': 'Conservation Sciences',
    'COP': 'Cellular/Organismal Physiology',
    'CPMS': 'Clinical Physiology and Movement Science',
    'CPSY': 'Child Psychology',
    'CSCI': 'Computer Science',
    'CSCL': 'Cultural Stdy/Comparative Lit',
    'CSE': 'Coll of Science, Engineering',
    'CSOM': 'Carlson School of Management',
    'CSPH': 'Ctr for Spirituality/Healing',
    'CVM': 'Veterinary Medicine',
    'DAKO': 'Dakota',
    'DBLN': 'Study Abroad in Dublin',
    'DDS': 'Doctor of Dental Surgery',
    'DENT': 'Dentistry',
    'DERM': 'Dermatology',
    'DES': 'Design',
    'DH': 'Dental Hygiene',
    'DNCE': 'Dance',
    'DSCI': 'Data Science',
    'DSSC': 'Develpmt Std and Soc Change',
    'DT': 'Dental Therapy',
    'DTCH': 'Dutch',
    'EAS': 'East Asian Studies',
    'ECDR': 'Ecuador',
    'ECON': 'Economics',
    'ECP': 'Experimental and Clinical Phar',
    'EDHD': 'Educational/Human Development',
    'EDUC': 'Education',
    'EE': 'Electrical & Computer Eng',
    'EEB': 'Ecology, Evolution, and Behav',
    'EMMD': 'Emergency Medicine',
    'EMS': 'Early Modern Studies',
    'ENDO': 'Endodontics',
    'ENGL': 'English:  Literature',
    'ENGW': 'English: Creative Writing',
    'ENT': 'Entomology',
    'ENTR': 'Entrepreneurship',
    'EPSY': 'Educational Psychology',
    'ESCI': 'Earth Sciences',
    'ESL': 'English as a Second Language',
    'ESPM': 'Environment Sci, Policy, Mgmt',
    'FDSY': 'Food Systems',
    'FIN': 'Finnish',
    'FINA': 'Finance',
    'FLOR': 'Study Abroad in Florence',
    'FM': 'Financial Mathematics',
    'FMCH': 'Family Med & Community Health',
    'FNRM': 'Forest and Natural Res. Mgmt.',
    'FOST': 'Foreign Study',
    'FREN': 'French',
    'FRIT': 'French and Italian',
    'FSCN': 'Food Science and Nutrition',
    'FSOS': 'Family Social Science',
    'FSSP': 'Foreign Study - Spain',
    'FW': 'Fisheries and Wildlife',
    'GCC': 'Grand Challenge Curriculum',
    'GCD': 'Genetics, Cell Biol/Developmnt',
    'GDBA': 'Global Doctorate of Business',
    'GDES': 'Graphic Design',
    'GEND': 'General Dentistry',
    'GEOG': 'Geography',
    'GER': 'German',
    'GERI': 'Geriatrics',
    'GERO': 'Gerontology',
    'GHSR': 'Global Health & Soc Respnsb',
    'GIS': 'Geographic Information Science',
    'GLBT': 'Gay, Lesbian, Bisexual, Transg',
    'GLOS': 'Global Studies',
    'GRAD': 'Graduate School',
    'GRK': 'Greek',
    'GSD': 'German,Scandinavian, and Dutch',
    'GWSS': 'Gender, Women, & Sexuality Std',
    'HCOL': 'Honors Colloquia',
    'HEBR': 'Hebrew',
    'HECU': 'Higher Ed Consortium Urban Aff',
    'HINF': 'Health Informatics',
    'HIST': 'History',
    'HMED': 'History of Medicine',
    'HMNG': 'Hmong',
    'HNDI': 'Hindi',
    'HNUR': 'Hindi and Urdu',
    'HORT': 'Horticultural Science',
    'HRIR': 'Human Resources/Indus Rel',
    'HSCI': 'History of Science and Tech',
    'HSEM': 'Honors Seminar',
    'HSEX': 'Human Sexuality',
    'HSG': 'Housing Studies',
    'HSM': 'Health Services Management',
    'HSPH': 'Heritage Studies & Public Hist',
    'HUMF': 'Human Factors',
    'IBH': 'Integrated Behavioral Health',
    'IBUS': 'International Business',
    'ICP': 'Inter-College Program',
    'ID': 'Interdepartamental Study',
    'IDES': 'Interior Design',
    'IDSC': 'Information and Decision Sci',
    'IE': 'Industrial Engineering',
    'IFSL': 'Integrated Food Systems Leadership',
    'IMBA': 'Industry Master of Buisness Administration',
    'INAR': 'Interdisciplinary Archaeologic',
    'INET': 'Information Networking',
    'INMD': 'Interdisciplinary Medicine',
    'INS': 'Insurance and Risk Management',
    'IREL': 'Interprsnl Relations Research',
    'ITAL': 'Italian',
    'JOUR': 'Journalism & Mass Communicat',
    'JPN': 'Japanese',
    'JWST': 'Jewish Studies',
    'KIN': 'Kinesiology',
    'KNYA': 'Kenya',
    'KOR': 'Korean',
    'LA': 'Landscape Architecture',
    'LAAS': 'Land and Atmospheric Science',
    'LAMP': 'Laboratory Medicine and Path',
    'LANG': 'Language Centr CLA Courseshare',
    'LAS': 'Latin American Studies',
    'LASK': 'Learning and Academic Skills',
    'LAT': 'Latin',
    'LAW': 'Law School',
    'LEAD': 'Leadership Education',
    'LGTT': 'Language, Teaching, and Technology',
    'LING': 'Linguistics',
    'LNDN': 'Study Abroad in London',
    'MABA': 'Masters of Appl Bus Analytics',
    'MADR': 'Madrid Learning Abroad Program',
    'MATH': 'Mathematics',
    'MATS': 'Materials Science',
    'MBA': 'Master of Business Admin',
    'MBS': 'Master of Biological Sciences',
    'MBT': 'Master of Business Taxation',
    'MCDG': 'Mol Cell Devlpmental Biol/Gene',
    'MCOM': 'Managerial Communications',
    'MDI': 'Medical Device Innovation',
    'MDP': 'Master of Development Practice',
    'MDS': 'Multidisciplinary Studies',
    'ME': 'Mechanical Engineering',
    'MED': 'Medicine',
    'MEDC': 'Medicinal Chemistry',
    'MEST': 'Medieval Studies',
    'MGMT': 'Management',
    'MICA': 'Microbiol/Immun/Cancer Biology',
    'MICB': 'Microbiology',
    'MICE': 'Microbial Engineering',
    'MIL': 'Military Science',
    'MILI': 'Medical Industry Leadrshp Inst',
    'MIMB': 'Medical Industry MBA',
    'MIMS': 'Moving Image Studies',
    'MKTG': 'Marketing',
    'MLK': 'Martin Luther King, Jr Program',
    'MLSP': 'Medical Laboratory Sciences Pr',
    'MM': 'Manufacturing Operations Mgmt',
    'MONT': 'Study Abroad in Montpellier',
    'MORT': 'Mortuary Science',
    'MOT': 'Management of Technology',
    'MPHY': 'Medical Physics',
    'MRCO': 'Arabic Lang/Culture in Morocco',
    'MSBA': 'Masters of Business Analytics',
    'MSF': 'Master of Science in Finance',
    'MSID': 'MN Studies in Intl Devel Prog',
    'MSMK': 'Master of Marketing',
    'MST': 'Museum Studies',
    'MTHE': 'Mathematics Education',
    'MUED': 'Music Education',
    'MULT': 'Multi-Inst Cross Registration',
    'MUS': 'Music',
    'MUSA': 'Music Applied',
    'NAV': 'Naval Science',
    'NEUR': 'Neurology',
    'NOR': 'Norwegian',
    'NR': 'Natural Resources Sci and Mgmt',
    'NSC': 'Neuroscience',
    'NSCI': 'Neuroscience Department',
    'NSU': 'Neurosurgery',
    'NURS': 'Nursing',
    'NUTR': 'Nutrition',
    'OBIO': 'Oral Biology',
    'OBST': 'Obstetrics and Gynecology',
    'OCS': 'Off-Campus Study',
    'OJIB': 'Ojibwe',
    'OLPD': 'Org Leadership, Policy & Dev',
    'OPH': 'Ophthalmology',
    'ORSU': 'Orthopaedic Surgery',
    'OSUR': 'Oral and Maxillofacial Surgery',
    'OT': 'Occupational Therapy',
    'OTHO': 'Orthodontics',
    'OTOL': 'Otolaryngology',
    'OUE': 'Office of Undergrad Education',
    'PA': 'Public Affairs',
    'PATH': 'Pathology',
    'PDEN': 'Pediatric Dentistry',
    'PDES': 'Product Design',
    'PE': 'Physical Education',
    'PED': 'Pediatrics',
    'PERO': 'Periodontics',
    'PHAR': 'Pharmacy',
    'PHCL': 'Pharmacology',
    'PHIL': 'Philosophy',
    'PHM': 'Pharmaceutics',
    'PHSL': 'Physiology',
    'PHYS': 'Physics',
    'PLPA': 'Plant Pathology',
    'PLSC': 'Plant Science',
    'PMB': 'Plant and Microbial Biology',
    'PMED': 'Physical Med & Rehabilitation',
    'POL': 'Political Science',
    'PORT': 'Portuguese',
    'POUL': 'Poultry Health',
    'PROS': 'Prosthodontics',
    'PSY': 'Psychology',
    'PT': 'Physical Therapy',
    'PUBH': 'Public Health',
    'RAD': 'Radiology',
    'REC': 'Recreation, Park, and Leisure Studies',
    'RELS': 'Religious Studies',
    'RM': 'Retail Merchandising',
    'ROB': 'Robotics',
    'ROME': 'Study Abroad in Rome',
    'RSC': 'Rehabilitation Science',
    'RUSS': 'Russian',
    'SACP': 'Social, Adm, and Clinical Phar',
    'SAGR': 'Sustainable Agricultural Syst',
    'SAPH': 'Social/Administrative Pharmacy',
    'SCAN': 'Scandinavian',
    'SCB': 'Stem Cell Biology',
    'SCIC': 'Scientific Computation',
    'SCLY': 'Study Abroad in Sicily',
    'SCMC': 'Studies in Cinema Media Cultur',
    'SCO': 'Supply Chain and Operations',
    'SDNY': 'Study Abroad in Sydney',
    'SENG': 'Software Engineering',
    'SFS': 'School for Field Studies',
    'SLHS': 'Speech-Language-Hearing Sci',
    'SMGT': 'Sport Management',
    'SMLI': 'Somali',
    'SNGL': 'Senegal',
    'SOC': 'Sociology',
    'SOIL': 'Soil, Water, and Climate',
    'SPAN': 'Spanish',
    'SPPT': 'Spanish and Portuguese',
    'SSM': 'Sustainable Systems Management',
    'SST': 'Studies of Science and Tech',
    'ST': 'Security Technologies',
    'STAT': 'Statistics',
    'SURG': 'Surgery',
    'SUST': 'Sustainability Studies',
    'SW': 'Social Work',
    'SWAH': 'Swahili',
    'SWED': 'Swedish',
    'TH': 'Theatre Arts',
    'THAI': 'MSID Program in Thailand',
    'TLDO': 'Toledo International Program',
    'TMDP': 'TMD & Orofacial Pain',
    'TRAD': 'Therapeutic Radiology',
    'TRIN': 'Translation and Interpreting',
    'TXCL': 'Toxicology',
    'UC': 'University College',
    'URBS': 'Urban Studies',
    'URDU': 'Urdu',
    'UROL': 'Urologic Surgery',
    'VBS': 'Veterinary & Biomedical Sci',
    'VCS': 'Veterinary Clinical Sciences',
    'VMBA': 'Vienna Executive MBA',
    'VMED': 'Veterinary Medicine, Graduate',
    'VPM': 'Veterinary Population Medicine',
    'WRIT': 'Writing Studies',
    'WRS': 'Water Resources Science',
    'YOST': 'Youth Development and Research',
    }

libed_mapping = {
    'AH': 'Arts/Humanities',
    'BIOL': 'Biological Sciences',
    'CIV': 'Civic Life and Ethics',
    'ENV': 'Environment',
    'GP': 'Global Perspectives',
    'IP': 'International Perspective Theme',
    'HIS': 'Historical Perspectives',
    'LITR': 'Literature',
    'MATH': 'Mathematical Thinking',
    'PHYS': 'Physical Sciences',
    'DSJ': 'Race, Power, and Justice in the United States',
    'SOCS': 'Social Sciences',
    'TS': 'Technology and Society',
    'WI': 'Writing Intensive',
    'HON': 'Honors',
    'FR SEMINAR': 'Freshman Seminar'
}
grade_mapping = {
    'A+': 4.3,
    'A': 4.0,
    'A-': 3.667,
    'B+': 3.333,
    'B': 3.0,
    'B-': 2.667,
    'C+': 2.333,
    'C': 2.0,
    'C-': 1.667,
    'D+': 1.333,
    'D': 1.0,
    'F': 0
}
