"""
This file has constant definitions for mappings from deptartment abbreviations to their actual name,
libed mapping from their abbreviations to actual name, and grade mapping from letters to GPA.
These may need to be edited manually on the creation of new departments, or changes to libed names but
these are infrequent and can be done by hand.
"""

dept_mapping = {
    "UMNTC": {
        "AAS": "Asian American Studies",
        "ABUS": "Applied Business",
        "ACCT": "Accounting",
        "ACL": "Arts and Cultural Leadership",
        "ADDS": "Addiction Studies",
        "ADES": "Apparel Design",
        "ADPY": "Adult Psychiatry",
        "AECM": "Ag Educ, Comm & Mktg",
        "AEM": "Aerospace Engineering and Mech",
        "AFEE": "Agriculture, Food, and Environment Education",
        "AFRO": "African Amer & African Studies",
        "AGRO": "Agronomy and Plant Genetics",
        "AHS": "Academic Health Center Shared",
        "AIM": "Agricultural Industries and Marketing",
        "AIR": "Aerospace Studies",
        "ALL": "Asian Languages and Literature",
        "AMES": "Asian & Middle Eastern Studies",
        "AMIN": "American Indian Studies",
        "AMST": "American Studies",
        "ANAT": "Anatomy",
        "ANES": "Anesthesiology",
        "ANSC": "Animal Science",
        "ANTH": "Anthropology",
        "APEC": "Applied Economics",
        "APS": "Applied Professional Studies",
        "APSC": "Applied Plant Sciences",
        "APST": "Apparel Studies",
        "ARAB": "Arabic",
        "ARCH": "Architecture",
        "ARGN": "Study Abroad in Argentina",
        "ARTH": "Art History",
        "ARTS": "Art",
        "ASCL": "Applied Sciences Leadership",
        "ASL": "American Sign Language",
        "AST": "Astronomy",
        "BA": "Business Administration",
        "BBE": "Bioproducts and Biosystems Eng",
        "BCLA": "CAPA Barcelona Study Abr Prgm",
        "BIOC": "Biochemistry",
        "BIOL": "Biology",
        "BLAW": "Business Law",
        "BMEN": "Biomedical Engineering",
        "BSE": "Biology, Society, and Environ",
        "BTHX": "Bioethics, Center for",
        "CAPY": "Child & Adolescent Psychiatry",
        "CDED": "Continuing Dental Education",
        "CEGE": "Civil, Environ, and Geo-Engin",
        "CESP": "Commun Engage Scholars Program",
        "CFAN": "Col of Food, Agr & Nat Res Sci",
        "CGSC": "Cognitive Science",
        "CHEM": "Chemistry",
        "CHEN": "Chemical Engineering",
        "CHIC": "Chicano Studies",
        "CHMB": "China Executive MBA",
        "CHN": "Chinese",
        "CHPH": "Chemical Physics",
        "CI": "Curriculum and Instruction",
        "CIVE": "Civic Engagement",
        "CL": "Comparative Literature",
        "CLA": "College of Liberal Arts",
        "CMB": "Comparative & Molecular Biosci",
        "CMBA": "Carlson Executive MBA",
        "CMGT": "Construction Management",
        "CNES": "Classical and Near Eastern Religions and Cultures",
        "CNRC": "Classical/Near Eastern Rel/Cul",
        "COMM": "Communication Studies",
        "CONS": "Conservation Sciences",
        "COP": "Cellular/Organismal Physiology",
        "CPMS": "Clinical Physiology and Movement Science",
        "CPSY": "Child Psychology",
        "CSCI": "Computer Science",
        "CSCL": "Cultural Stdy/Comparative Lit",
        "CSE": "Coll of Science, Engineering",
        "CSOM": "Carlson School of Management",
        "CSPH": "Ctr for Spirituality/Healing",
        "CVM": "Veterinary Medicine",
        "DAKO": "Dakota",
        "DBLN": "Study Abroad in Dublin",
        "DDS": "Doctor of Dental Surgery",
        "DENT": "Dentistry",
        "DERM": "Dermatology",
        "DES": "Design",
        "DH": "Dental Hygiene",
        "DNCE": "Dance",
        "DSCI": "Data Science",
        "DSSC": "Develpmt Std and Soc Change",
        "DT": "Dental Therapy",
        "DTCH": "Dutch",
        "EAS": "East Asian Studies",
        "ECDR": "Ecuador",
        "ECON": "Economics",
        "ECP": "Experimental and Clinical Phar",
        "EDHD": "Educational/Human Development",
        "EDUC": "Education",
        "EE": "Electrical & Computer Eng",
        "EEB": "Ecology, Evolution, and Behav",
        "EMMD": "Emergency Medicine",
        "EMS": "Early Modern Studies",
        "ENDO": "Endodontics",
        "ENGL": "English:  Literature",
        "ENGW": "English: Creative Writing",
        "ENT": "Entomology",
        "ENTR": "Entrepreneurship",
        "EPSY": "Educational Psychology",
        "ESCI": "Earth Sciences",
        "ESL": "English as a Second Language",
        "ESPM": "Environment Sci, Policy, Mgmt",
        "FDSY": "Food Systems",
        "FIN": "Finnish",
        "FINA": "Finance",
        "FLOR": "Study Abroad in Florence",
        "FM": "Financial Mathematics",
        "FMCH": "Family Med & Community Health",
        "FNRM": "Forest and Natural Res. Mgmt.",
        "FOST": "Foreign Study",
        "FREN": "French",
        "FRIT": "French and Italian",
        "FSCN": "Food Science and Nutrition",
        "FSOS": "Family Social Science",
        "FSSP": "Foreign Study - Spain",
        "FW": "Fisheries and Wildlife",
        "GCC": "Grand Challenge Curriculum",
        "GCD": "Genetics, Cell Biol/Developmnt",
        "GDBA": "Global Doctorate of Business",
        "GDES": "Graphic Design",
        "GEND": "General Dentistry",
        "GEOG": "Geography",
        "GER": "German",
        "GERI": "Geriatrics",
        "GERO": "Gerontology",
        "GHSR": "Global Health & Soc Respnsb",
        "GIS": "Geographic Information Science",
        "GLBT": "Gay, Lesbian, Bisexual, Transg",
        "GLOS": "Global Studies",
        "GRAD": "Graduate School",
        "GRK": "Greek",
        "GSD": "German,Scandinavian, and Dutch",
        "GWSS": "Gender, Women, & Sexuality Std",
        "HCOL": "Honors Colloquia",
        "HEBR": "Hebrew",
        "HECU": "Higher Ed Consortium Urban Aff",
        "HINF": "Health Informatics",
        "HIST": "History",
        "HMED": "History of Medicine",
        "HMNG": "Hmong",
        "HNDI": "Hindi",
        "HNUR": "Hindi and Urdu",
        "HORT": "Horticultural Science",
        "HRIR": "Human Resources/Indus Rel",
        "HSCI": "History of Science and Tech",
        "HSEM": "Honors Seminar",
        "HSEX": "Human Sexuality",
        "HSG": "Housing Studies",
        "HSM": "Health Services Management",
        "HSPH": "Heritage Studies & Public Hist",
        "HUMF": "Human Factors",
        "IBH": "Integrated Behavioral Health",
        "IBUS": "International Business",
        "ICP": "Inter-College Program",
        "ID": "Interdepartamental Study",
        "IDES": "Interior Design",
        "IDSC": "Information and Decision Sci",
        "IE": "Industrial Engineering",
        "IFSL": "Integrated Food Systems Leadership",
        "IMBA": "Industry Master of Buisness Administration",
        "INAR": "Interdisciplinary Archaeologic",
        "INET": "Information Networking",
        "INMD": "Interdisciplinary Medicine",
        "INS": "Insurance and Risk Management",
        "IREL": "Interprsnl Relations Research",
        "ITAL": "Italian",
        "JOUR": "Journalism & Mass Communicat",
        "JPN": "Japanese",
        "JWST": "Jewish Studies",
        "KIN": "Kinesiology",
        "KNYA": "Kenya",
        "KOR": "Korean",
        "LA": "Landscape Architecture",
        "LAAS": "Land and Atmospheric Science",
        "LAMP": "Laboratory Medicine and Path",
        "LANG": "Language Centr CLA Courseshare",
        "LAS": "Latin American Studies",
        "LASK": "Learning and Academic Skills",
        "LAT": "Latin",
        "LAW": "Law School",
        "LEAD": "Leadership Education",
        "LGTT": "Language, Teaching, and Technology",
        "LING": "Linguistics",
        "LNDN": "Study Abroad in London",
        "MABA": "Masters of Appl Bus Analytics",
        "MADR": "Madrid Learning Abroad Program",
        "MATH": "Mathematics",
        "MATS": "Materials Science",
        "MBA": "Master of Business Admin",
        "MBS": "Master of Biological Sciences",
        "MBT": "Master of Business Taxation",
        "MCDG": "Mol Cell Devlpmental Biol/Gene",
        "MCOM": "Managerial Communications",
        "MDI": "Medical Device Innovation",
        "MDP": "Master of Development Practice",
        "MDS": "Multidisciplinary Studies",
        "ME": "Mechanical Engineering",
        "MED": "Medicine",
        "MEDC": "Medicinal Chemistry",
        "MEST": "Medieval Studies",
        "MGMT": "Management",
        "MICA": "Microbiol/Immun/Cancer Biology",
        "MICB": "Microbiology",
        "MICE": "Microbial Engineering",
        "MIL": "Military Science",
        "MILI": "Medical Industry Leadrshp Inst",
        "MIMB": "Medical Industry MBA",
        "MIMS": "Moving Image Studies",
        "MKTG": "Marketing",
        "MLK": "Martin Luther King, Jr Program",
        "MLSP": "Medical Laboratory Sciences Pr",
        "MM": "Manufacturing Operations Mgmt",
        "MONT": "Study Abroad in Montpellier",
        "MORT": "Mortuary Science",
        "MOT": "Management of Technology",
        "MPHY": "Medical Physics",
        "MRCO": "Arabic Lang/Culture in Morocco",
        "MSBA": "Masters of Business Analytics",
        "MSF": "Master of Science in Finance",
        "MSID": "MN Studies in Intl Devel Prog",
        "MSMK": "Master of Marketing",
        "MST": "Museum Studies",
        "MTHE": "Mathematics Education",
        "MUED": "Music Education",
        "MULT": "Multi-Inst Cross Registration",
        "MUS": "Music",
        "MUSA": "Music Applied",
        "NAV": "Naval Science",
        "NEUR": "Neurology",
        "NOR": "Norwegian",
        "NR": "Natural Resources Sci and Mgmt",
        "NSC": "Neuroscience",
        "NSCI": "Neuroscience Department",
        "NSU": "Neurosurgery",
        "NURS": "Nursing",
        "NUTR": "Nutrition",
        "OBIO": "Oral Biology",
        "OBST": "Obstetrics and Gynecology",
        "OCS": "Off-Campus Study",
        "OJIB": "Ojibwe",
        "OLPD": "Org Leadership, Policy & Dev",
        "OPH": "Ophthalmology",
        "ORSU": "Orthopaedic Surgery",
        "OSUR": "Oral and Maxillofacial Surgery",
        "OT": "Occupational Therapy",
        "OTHO": "Orthodontics",
        "OTOL": "Otolaryngology",
        "OUE": "Office of Undergrad Education",
        "PA": "Public Affairs",
        "PATH": "Pathology",
        "PDEN": "Pediatric Dentistry",
        "PDES": "Product Design",
        "PE": "Physical Education",
        "PED": "Pediatrics",
        "PERO": "Periodontics",
        "PHAR": "Pharmacy",
        "PHCL": "Pharmacology",
        "PHIL": "Philosophy",
        "PHM": "Pharmaceutics",
        "PHSL": "Physiology",
        "PHYS": "Physics",
        "PLPA": "Plant Pathology",
        "PLSC": "Plant Science",
        "PMB": "Plant and Microbial Biology",
        "PMED": "Physical Med & Rehabilitation",
        "POL": "Political Science",
        "PORT": "Portuguese",
        "POUL": "Poultry Health",
        "PROS": "Prosthodontics",
        "PSY": "Psychology",
        "PT": "Physical Therapy",
        "PUBH": "Public Health",
        "RAD": "Radiology",
        "REC": "Recreation, Park, and Leisure Studies",
        "RELS": "Religious Studies",
        "RM": "Retail Merchandising",
        "ROB": "Robotics",
        "ROME": "Study Abroad in Rome",
        "RSC": "Rehabilitation Science",
        "RUSS": "Russian",
        "SACP": "Social, Adm, and Clinical Phar",
        "SAGR": "Sustainable Agricultural Syst",
        "SAPH": "Social/Administrative Pharmacy",
        "SCAN": "Scandinavian",
        "SCB": "Stem Cell Biology",
        "SCIC": "Scientific Computation",
        "SCLY": "Study Abroad in Sicily",
        "SCMC": "Studies in Cinema Media Cultur",
        "SCO": "Supply Chain and Operations",
        "SDNY": "Study Abroad in Sydney",
        "SENG": "Software Engineering",
        "SFS": "School for Field Studies",
        "SLHS": "Speech-Language-Hearing Sci",
        "SMGT": "Sport Management",
        "SMLI": "Somali",
        "SNGL": "Senegal",
        "SOC": "Sociology",
        "SOIL": "Soil, Water, and Climate",
        "SPAN": "Spanish",
        "SPPT": "Spanish and Portuguese",
        "SSM": "Sustainable Systems Management",
        "SST": "Studies of Science and Tech",
        "ST": "Security Technologies",
        "STAT": "Statistics",
        "SURG": "Surgery",
        "SUST": "Sustainability Studies",
        "SW": "Social Work",
        "SWAH": "Swahili",
        "SWED": "Swedish",
        "TH": "Theatre Arts",
        "THAI": "MSID Program in Thailand",
        "TLDO": "Toledo International Program",
        "TMDP": "TMD & Orofacial Pain",
        "TRAD": "Therapeutic Radiology",
        "TRIN": "Translation and Interpreting",
        "TXCL": "Toxicology",
        "UC": "University College",
        "URBS": "Urban Studies",
        "URDU": "Urdu",
        "UROL": "Urologic Surgery",
        "VBS": "Veterinary & Biomedical Sci",
        "VCS": "Veterinary Clinical Sciences",
        "VMBA": "Vienna Executive MBA",
        "VMED": "Veterinary Medicine, Graduate",
        "VPM": "Veterinary Population Medicine",
        "WRIT": "Writing Studies",
        "WRS": "Water Resources Science",
        "YOST": "Youth Development and Research",
    },
    "UMNDL": {
        "ACCT": "Accounting",
        "AMIN": "American Indian Studies",
        "ANTH": "Anthropology",
        "ART": "Art",
        "ASL": "American Sign Language",
        "AST": "Astronomy",
        "BA": "Business Analytics",
        "BCOM": "Business Communication",
        "BIOL": "Biology",
        "BLAW": "Business Law",
        "BMS": "BioMedical Sciences",
        "CC": "Coaching",
        "CE": "Civil Engineering",
        "CHE": "Chemical Engineering",
        "CHEM": "Chemistry",
        "CHIN": "Chinese",
        "CIA": "Consumer Insights & Analytics",
        "COMM": "Communication",
        "CRIM": "Criminology",
        "CS": "Computer Science",
        "CUE": "Cultural Entrepreneurship",
        "ECH": "Early Childhood Studies",
        "ECON": "Economics",
        "EDSE": "Education, Secondary",
        "EDUC": "Education",
        "EE": "Electrical Engineering",
        "EES": "Earth &amp; Environmental Sciences",
        "ENED": "Environmental Education",
        "ENGL": "English",
        "ES": "Environment and Sustainability",
        "EXSC": "Exercise Science",
        "FIN": "Finance",
        "FMED": "Family Medicine",
        "FORS": "Foreign Studies",
        "FR": "French",
        "FST": "Foreign Studies",
        "GEOG": "Geography",
        "GIS": "Geographic Information Science",
        "GRAD": "Graduate School",
        "GRD": "Graduate Summer Research",
        "HCM": "Health Care Management",
        "HIST": "History",
        "HLTH": "Health",
        "IE": "Industrial Engineering",
        "INTB": "International Business",
        "JOUR": "Journalism",
        "LING": "Linguistics",
        "MATH": "Mathematics",
        "MBA": "Master of Business Admin",
        "ME": "Mechanical Engineering",
        "MED": "Medicine",
        "MGTS": "Management Studies",
        "MIS": "Management Information Science",
        "MKTG": "Marketing",
        "MNMD": "Collaborative Medicine",
        "MPS": "Master of Professional Studies",
        "MST": "Museum Studies",
        "MU": "Music",
        "MULT": "Multi-Inst Cross Registration",
        "PETE": "Physical Education Teacher",
        "PHAR": "Pharmacy",
        "PHIL": "Philosophy",
        "PHYS": "Physics",
        "POL": "Political Science",
        "PSY": "Psychology",
        "SAFE": "Safety",
        "SOC": "Sociology",
        "SPAN": "Spanish",
        "SPED": "Special Education",
        "STAT": "Statistics",
        "SW": "Social Work",
        "TH": "Theatre",
        "UGRD": "Undergraduate Summer Research",
        "UST": "University Studies",
        "WRIT": "Writing Studies",
        "WRS": "Water Resources Science",
        "WS": "Women's Studies",
    },
    "UMNCR": {
        "AGEC": "Agricultural Economics",
        "AGRO": "Agronomy",
        "APLS": "Applied Studies",
        "BIOL": "Biology",
        "BM": "Bachelor of Manufacturing",
        "CA": "Computer Applications",
        "COMM": "Communication",
        "COMP": "Composition",
        "CRJS": "Criminal Justice",
        "ECE": "Early Childhood Education",
        "ECON": "Economics",
        "ED": "Education",
        "ENGL": "English",
        "FIN": "Finance",
        "GBUS": "General Business",
        "GNAG": "General Agriculture",
        "HSCI": "Health Science",
        "HSM": "Health Systems Management",
        "HUM": "Humanities",
        "IBUS": "International Business",
        "ITM": "Information Technology Mgmt",
        "LEAD": "Leadership",
        "MATH": "Mathematics",
        "MGMT": "Management",
        "MKTG": "Marketing",
        "MLS": "Medical Laboratory Science",
        "MULT": "Multi-Inst Cross Registration",
        "NATR": "Natural Resources",
        "PHIL": "Philosophy",
        "PHYS": "Physics",
        "PSY": "Psychology",
        "SE": "Software Engineering",
        "SOC": "Sociology",
        "SRM": "Sport & Recreation Management",
        "SUST": "Sustainability",
        "WRIT": "Writing",
    },
    "UMNMO": {
        "ARTS": "Art, Studio",
        "BIOL": "Biology",
        "CHEM": "Chemistry",
        "CMR": "Communication, Media, Rhetoric",
        "ECON": "Economics",
        "ED": "Education",
        "ENST": "Environmental Studies",
        "FOST": "Foreign Studies",
        "FREN": "French",
        "GEOL": "Geology",
        "HIST": "History",
        "HMSV": "Human Services",
        "IS": "Interdisciplinary Studies",
        "MGMT": "Management",
        "MULT": "Multi-Inst Cross Registration",
        "MUS": "Music",
        "NAIS": "Native Amer and Indigenous Std",
        "PHIL": "Philosophy",
        "POL": "Political Science",
        "PSY": "Psychology",
        "SPAN": "Spanish",
        "SSA": "Sport Studies and Athletics",
        "STAT": "Statistics",
        "TH": "Theatre Arts",
    },
    "UMNRO": {
        "BICB": "Biomed Inform & Comput Biology",
        "BIOL": "Biology",
        "CLI": "Center for Learning Innovation",
        "COMM": "Communication Studies",
        "ECHO": "Echocardiography",
        "ENGL": "English:  Literature",
        "MATH": "Mathematics",
        "PHYS": "Physics",
        "PSY": "Psychology",
        "PUBH": "Public Health",
        "RADI": "Radiography",
        "RESP": "Respiratory Care (Rochester)",
        "SONO": "Sonography",
        "WRIT": "Writing Studies",
    },
}

catalog_mapping = {
    "UMNCR": "umc",
    "UMNDL": "umd",
    "UMNMO": "umm",
    "UMNRO": "umr",
    "UMNTC": "umtc",
}

libed_mapping = {
    # College of Liberal Education
    "CLE - AH (Arts/Humanities)": "Arts/Humanities",
    "CLE - BIOL (Biological Sciences)": "Biological Sciences",
    "CLE - CIV (Civic Life and Ethics)": "Civic Life and Ethics",
    "CLE - ENV (Environment)": "Environment",
    "CLE - GP (Global Perspectives)": "Global Perspectives",
    "IP": "International Perspective Theme",  # This is obsolete, no longer utilized 
    "CLE - HIS (Historical Perspectives)": "Historical Perspectives",
    "CLE - LITR (Literature)": "Literature",
    "CLE - MATH (Mathematical Thinking)": "Mathematical Thinking",
    "CLE - MATH (Mathematical Thinking Core)": "Mathematical Thinking",  # This is an alias for the above
    "CLE - PHYS (Physical Sciences)": "Physical Sciences",
    "CLE - DSJ (Race, Power, and Justice US)": "Race, Power, and Justice in the United States",
    "CLE - DSJ (Diversity and Soc Justice US)": "Race, Power, and Justice in the United States",  # This is an alias for the above
    "CLE - SOCS (Social Sciences)": "Social Sciences",
    "CLE - TS (Technology and Society)": "Technology and Society",
    "CLE - WI (Writing Intensive)": "Writing Intensive",
    "CLE - HP (Historical Perspective Core)": "Historical Perspective",
    # Community Engagement Learning
    "CEL - SERV-LRNG (Service-Learning)": "Service Learning",
    "CELD - SERV-LRNG (Service-learning)": "Service Learning",  # Alias for above
    "CEL - FIELD STDY (Field Study)": "Field Study",
    "CEL - RESEARCH (Research)": "Research",
    "CEL - INTRN COOP (Internship/Co-op)": "Internship/Co-op",
    "CEL - PRACTICUM (Practicum)": "Practicum",
    "CEL - ENTREPREN (Entrepreneurship)": "Entrepreneurship",
    "CEL - STDNT TCHG (Student Teaching)": "Student Teaching",
    "CEL - CLINICAL (Clinical)": "Clinical",
    # Crookston
    "GE - COMMUNICAT (Goal 1 - Written/Oral Comm)": "Goal 1 - Written/Oral Comm",
    "GE - CR THINKG (Goal 2 - Critical Thinking)": "Goal 2 - Critical Thinking",
    "GE - BIOL SCI (Goal 3a - Biological Science)": "Goal 3a - Biological Science",
    "GE - PHYS SCI (Goal 3b - Physical Science)": "Goal 3b - Physical Science",
    "GE - MATH THINK (Goal 4 - Mathematical Thinking)": "Goal 4 - Mathematical Thinking",
    "GE - HI/BEH/SSC (Goal 5 - Hist & Behavrl/SocSci)": "Goal 5 - Hist & Behavrl/SocSci",
    "GE - HUMANITIES (Goal 6 - Hum: Arts/Lit/Phil)": "Goal 6 - Hum: Arts/Lit/Phil",
    "GE - HUMAN DIV (Goal 7 - Human Diversity)": "Goal 7 - Human Diversity",
    "GE - GLOB PERSP (Goal 8 - Global Perspective)": "Goal 8 - Global Perspective",
    "GE - ETH/CIV RE (Goal 9 - Eth/Civic Responsblty)": "Goal 9 - Eth/Civic Responsblty",
    "GE - PEOPLE/ENV (Goal 10 - People/Environment)": "Goal 10 - People/Environment",
    "MTC - MTC GOAL10 (People and the Environment)": "Goal 10 - People/Environment", # Alias for above
    # Duluth
    "DLE - CDIVERSITY (Cultural Diversity in the US)": "Cultural Diversity in the US",
    "DLE - FINE ARTS (Fine Arts)": "Fine Arts",
    "DLE - GLOBAL PER (Global Perspectives)": "Global Perspectives",
    "DLE - HUMANITIES (Humanities)": "Humanities",
    "DLE - LOGIC & QR (Logic & Quantitative Reasoning)": "Logic & Quantitative Reasoning",
    "DLE - NAT SCI (Natural Sciences)": "Natural Sciences",
    "MTC - MTC GOAL3 (Natural Sciences)": "Natural Sciences", # Alias for above
    "DLE - COMM & LAN (Oral Communication & Languages)": "Oral Communication & Languages",
    "DLE - SOC SCI (Social Sciences)": "Social Sciences",
    "DLE - SUSTAIN (Sustainability)": "Sustainability",
    "DLE - RACE JUST (Race, Power and Justice)": "Race, Power and Justice",
    "DLE - WRITING (Writing & Information Literacy)": "Writing & Information Literacy",
    # Morris
    "GER - ART/P (Artistic Performance)": "Artistic Performance",
    "GER - HUM (Communicatin,Lang,Lit,Phlosphy)": "Comm, Lang, Lit, & Philosophy",
    "GER - E/CR (E/CR)": "Ethical and Civic Responsibility",
    "GER - E/CR (Ethical & Civic Responsibility)": "Ethical and Civic Responsibility", # Alias for above
    "GER - FA (Fine Arts)": "Fine Arts",
    "GER - FA (FA)": "Fine Arts", # Alias for above
    "GER - HIST (Historical Perspectives)": "Historical Perspectives",
    "GER - HIST (Hist)": "Historical Perspectives", # Alias for above
    "GER - SS (Human Behvr,Socl Proces,Instns)": "Human Behvr, Socl Proces, Instns",
    "GER - HUM (Hum)": "Human Behvr, Socl Proces, Instns", # Alias for above
    "GER - HDIV (Human Diversity)" : "Human Diversity",
    "GER - IC (Intellectual Community)" : "Intellectual Community",
    "GER - IP (IP)": "International Perspectives",
    "GER - IP (International Perspectives)" : "International Perspectives", # Alias for above
    "GER - M/SR (Mathmatical/Symbolic Reasoning)": "Mathmatical/Symbolic Reasoning",
    "GER - ENVT (People and the Environment)": "People and the Environment",
    "GER - SCI-L (Physical & Biol Sci w/Lab)": "Physical & Biol Sci w/Lab",
    "GER - SCI (Physical & Biol Sci w/o Lab)": "Physical & Biol Sci w/o Lab",
    "GER - WL (World Language)": "World Language",
    "GER - WE (Writing Enriched)": "Writing Enriched",
    "GER - WLA (Writing for the Liberal Arts)": "Writing for Liberal Arts",
    # Other
    "HON - HON (Honors)": "Honors",
    "FSEM - FR SEMINAR (Freshman Seminar)": "Freshman Seminar",
    "TOP - TOPICS (Topics Course)": "Topics Course",
    "ONL - ONLINE (Online may be available)": "Online Available",
}
grade_mapping = {
    "A+": 4.3,
    "A": 4.0,
    "A-": 3.667,
    "B+": 3.333,
    "B": 3.0,
    "B-": 2.667,
    "C+": 2.333,
    "C": 2.0,
    "C-": 1.667,
    "D+": 1.333,
    "D": 1.0,
    "F": 0,
}


def term_to_name(term: int):
    retVal = ""
    if term % 10 == 5:
        retVal += "Summer "
    elif term % 10 == 9:
        retVal += "Fall "
    elif term % 10 == 3:
        retVal += "Spring "
    else:
        return "Invalid Term"

    term //= 10
    retVal += f"{1900 + (term)}"
    return retVal
